### ISSUE TITLE
Faltando metadados ou dados inválidos? 

### ISSUE THREAD

**Issue by raivil** [codigoquant/b3fileparser#4]
Olá,

Executei a leitura de um arquivo recente (2024-03-05) e tive errors por falta de metadados em MARKETS( id: 21) e CODBDI (codigos 92 e 93).
Não encontrei esses códigos na documentação da B3 en https://www.b3.com.br/data/files/33/67/B9/50/D84057102C784E47AC094EA8/SeriesHistoricas_Layout.pdf

Seria erro dos dados?
Arquivo usado: COTAHIST_D05032024.TXT

**Comment by codigoquant** [comment]
Corrigido na versão 0.1.5
